In [1]:



# Task 4

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Step 1: Organize content by release year.
df=pd.read_csv("cleaned_netflix_titles.csv")

# trying to filterout the old dated movie but i provide you the first movie and TV show.
modern_df=df[df['release_year']>=2000]
organized_df=modern_df.groupby(['release_year','type']).size()
print("Organize content by release year")
print(organized_df.head(10))

print("---------------------------------------------")
print("The first movie and Tv show:")
first_df=df.groupby('type').agg({'release_year':'min','title':'first'})
first_df

Organize content by release year
release_year  type
2000          Movie      33
              Tv Show     4
2001          Movie      40
              Tv Show     5
2002          Movie      44
              Tv Show     7
2003          Movie      51
              Tv Show     8
2004          Movie      55
              Tv Show     9
dtype: int64
---------------------------------------------
The first movie and Tv show:

         release_year                 title
type
Movie            1942  Dick Johnson Is Dead
Tv Show          1925             Ganglands

In [4]:
# Step 2: Calculate yearly content releases.

# Filter for modern titles (Year 2000 to present) to keep data focused
modern_df = df[df['release_year'] >= 2000]
yearly_content_df=modern_df.groupby(['release_year','type']).size().unstack()
yearly_content_df.head(10)

type          Movie  Tv Show
release_year
2000             33        4
2001             40        5
2002             44        7
2003             51        8
2004             55        9
2005             67       13
2006             82       14
2007             74       14
2008            113       22
2009            118       34

In [5]:
# Step 3: Identify growth and decline trends.

#  -> to find the growth and decline trend i need to evaluated yealy to yealry growing rate of movie and tv shows
#      so used pct_change() function to calculate the change from one year to the next. 

growth_trend=yearly_content_df.pct_change() *100
print("---  Year-over-Year Growth/Decline Trends (%) ---")
print(growth_trend.tail(10).round(2))

---  Year-over-Year Growth/Decline Trends (%) ---
type          Movie  Tv Show
release_year
2012          19.31    57.50
2013          30.06    -3.17
2014          17.33    44.26
2015          50.00    80.68
2016          66.16    52.83
2017          16.26     9.05
2018           0.26    43.02
2019         -17.47     4.75
2020         -18.33     9.82
2021         -46.42   -27.75